# Data Preprocessing Tools

## Importing the libraries

In [130]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import cross_val_score
from scipy import stats
from sklearn.inspection import permutation_importance
from matplotlib import pyplot as plt

## Importing the dataset

In [131]:
dataset = pd.read_csv('ML.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [132]:
x

array([[2.666666667, 'Afghanistan', nan, ..., 'Always problematic\t',
        'Sometimes problematic\t', 'Always problematic\t'],
       [2.666666667, 'Morocco', 18.0, ..., 'Not problematic\t',
        'Always problematic\t', 'Not problematic\t'],
       [3.166666667, 'Iran', 21.0, ..., 'Sometimes problematic\t',
        'Not problematic\t', 'Sometimes problematic\t'],
       ...,
       [nan, 'Afghanistan', 21.0, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, 'Afghanistan', 19.0, ..., nan, nan, nan]], dtype=object)

In [133]:
y

array(['Somewhat dissatisfied', 'Somewhat satisfied',
       'Neither satisfied nor dissatisfied', 'Somewhat satisfied',
       'Neither satisfied nor dissatisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat satisfied',
       'Neither satisfied nor dissatisfied',
       'Neither satisfied nor dissatisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat satisfied',
       'Somewhat dissatisfied', 'Somewhat satisfied',
       'Extremely satisfied', 'Somewhat satisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat dissatisfied',
       'Somewhat satisfied', 'Somewhat satisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat satisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat satisfied', 'Somewhat satisfied',
       nan, 'Somewhat satisfied', 'Neither satisfied nor dissatisfied',
       'Somewhat satisfied', 'Somewhat satisfied', 'Somewhat satisfied',
       'Somewhat satisfied', 'Somewhat satisfied', '

## Taking care of missing data

In [134]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer.fit(x)
x = imputer.transform(x)

In [135]:
y = y.reshape(-1, 1)
from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer1.fit(y)
y = imputer1.transform(y)

In [136]:
x

array([[2.666666667, 'Afghanistan', 20.0, ..., 'Always problematic\t',
        'Sometimes problematic\t', 'Always problematic\t'],
       [2.666666667, 'Morocco', 18.0, ..., 'Not problematic\t',
        'Always problematic\t', 'Not problematic\t'],
       [3.166666667, 'Iran', 21.0, ..., 'Sometimes problematic\t',
        'Not problematic\t', 'Sometimes problematic\t'],
       ...,
       [3.0, 'Afghanistan', 21.0, ..., 'Sometimes problematic\t',
        'Sometimes problematic\t', 'Sometimes problematic\t'],
       [3.0, 'Pakistan', 20.0, ..., 'Sometimes problematic\t',
        'Sometimes problematic\t', 'Sometimes problematic\t'],
       [3.0, 'Afghanistan', 19.0, ..., 'Sometimes problematic\t',
        'Sometimes problematic\t', 'Sometimes problematic\t']],
      dtype=object)

In [137]:
y

array([['Somewhat dissatisfied'],
       ['Somewhat satisfied'],
       ['Neither satisfied nor dissatisfied'],
       ['Somewhat satisfied'],
       ['Neither satisfied nor dissatisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Neither satisfied nor dissatisfied'],
       ['Neither satisfied nor dissatisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat dissatisfied'],
       ['Somewhat satisfied'],
       ['Extremely satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat dissatisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied'],
       ['Somewhat satisfied

## Encoding categorical data

### Encoding the Independent Variable

In [138]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(sparse = False),[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
                                                                  ,21,22,23,24,25,26,27,28,29,30,31,32,33,34] )] , remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [139]:
np.shape(x)

(300, 220)

### Splitting the dataset into the Training set and Test set

In [140]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

C:\Users\SN\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [141]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .2)

## Fitting the Logistic Model

In [163]:
from sklearn.linear_model import LogisticRegression
classifier_lr1 = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier_lr1.fit(x_train, y_train)


LogisticRegression(max_iter=10000, random_state=0)

In [164]:
y_pred_lr = classifier_lr1.predict(x_test)
print(np.concatenate((y_pred_lr.reshape(len(y_pred_lr),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 1]
 [4 3]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [2 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [1 4]
 [4 1]
 [2 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 1]
 [4 4]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]]


In [165]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
accuracy_score(y_test, y_pred_lr)

[[ 1  0  0  6]
 [ 0  3  0  5]
 [ 0  0  0  1]
 [ 1  2  0 41]]


0.75

In [166]:
# Results by cross validation
scores_lr1 = cross_val_score(classifier_lr1, x, y, cv=4)
np.mean(scores_lr)

0.7366666666666667

## K-Nearest Model

In [227]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [332]:
y_pred_knn = classifier_knn.predict(x_test)
print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1), y_test.reshape(len(y_test),1)),1))

[[4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [1 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [4 3]
 [4 4]
 [2 2]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [2 3]]


C:\Users\ACER\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [333]:
###Confusion Matrix

In [334]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)
accuracy_score(y_test, y_pred_knn)

[[ 0  0  0  4]
 [ 0  2  0  5]
 [ 0  1  0  3]
 [ 1  0  0 44]]


0.7666666666666667

In [231]:
# Results by cross validation
scores_knn = cross_val_score(classifier_knn, x, y, cv=4)
np.mean(scores_knn)

C:\Users\ACER\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\ACER\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims`

0.7333333333333334

In [232]:
## Support Vector algorithm

In [233]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'linear', random_state = 0)
classifier_svm.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [234]:
y_pred_svm = classifier_svm.predict(x_test)
print(np.concatenate((y_pred_svm.reshape(len(y_pred_svm),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [1 2]
 [4 2]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [2 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [3 3]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 4]
 [1 3]
 [4 4]
 [4 4]
 [2 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 4]
 [2 3]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


In [235]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
accuracy_score(y_test, y_pred_svm)

[[ 2  0  0  3]
 [ 1  2  0  5]
 [ 1  1  1  1]
 [ 0  4  0 39]]


0.7333333333333333

In [236]:
# Results by cross validation
scores_knn = cross_val_score(classifier_svm, x, y, cv=4)
np.mean(scores_svm)

0.6733333333333335

In [237]:
## Kernal Algorithm

In [238]:
from sklearn.svm import SVC
classifier_kernal = SVC(kernel = 'rbf', random_state = 0)
classifier_kernal.fit(x_train, y_train)

SVC(random_state=0)

In [239]:
y_pred_kernal = classifier_kernal.predict(x_test)
print(np.concatenate((y_pred_kernal.reshape(len(y_pred_kernal),1), y_test.reshape(len(y_test),1)),1))

[[4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 2]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


In [240]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_kernal)
print(cm)
accuracy_score(y_test, y_pred_kernal)

[[ 0  0  0  5]
 [ 0  0  0  8]
 [ 0  0  0  4]
 [ 0  0  0 43]]


0.7166666666666667

In [241]:
# Results by cross validation
scores_kernal = cross_val_score(classifier_kernal, x, y, cv=4)
np.mean(scores_kernal)

0.78

In [242]:
## Naive Bayes

In [243]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [244]:
y_pred_nb = classifier_nb.predict(x_test)
print(np.concatenate((y_pred_nb.reshape(len(y_pred_nb),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 2]
 [2 4]
 [4 4]
 [1 4]
 [1 4]
 [4 2]
 [1 2]
 [4 1]
 [4 4]
 [1 4]
 [1 4]
 [4 1]
 [4 4]
 [4 4]
 [2 4]
 [2 2]
 [2 4]
 [2 4]
 [4 4]
 [1 4]
 [4 4]
 [1 4]
 [1 4]
 [2 3]
 [1 2]
 [4 2]
 [4 4]
 [2 4]
 [4 4]
 [2 2]
 [4 4]
 [4 3]
 [1 4]
 [1 4]
 [4 4]
 [2 4]
 [1 4]
 [2 4]
 [4 4]
 [1 4]
 [1 4]
 [2 4]
 [4 3]
 [2 4]
 [1 4]
 [1 1]
 [4 4]
 [4 4]
 [4 1]
 [4 2]
 [2 4]
 [4 4]
 [1 4]
 [4 3]
 [1 4]
 [1 4]
 [4 4]
 [1 4]
 [4 4]]


In [245]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)
accuracy_score(y_test, y_pred_nb)

[[ 2  0  0  3]
 [ 3  2  0  3]
 [ 0  1  0  3]
 [17 10  0 16]]


0.3333333333333333

In [246]:
# Results by cross validation
scores_nb = cross_val_score(classifier_nb, x, y, cv=4)
np.mean(scores_nb)

0.3766666666666666

In [247]:
## Decision Tree

In [248]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=0)

In [249]:
y_pred_dt = classifier_dt.predict(x_test)
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [0 2]
 [2 2]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [2 2]
 [1 2]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [2 4]
 [2 3]
 [2 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [2 1]
 [4 4]
 [4 4]
 [4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


In [250]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)
accuracy_score(y_test, y_pred_dt)

[[ 0  0  0  0  0]
 [ 0  1  1  0  3]
 [ 1  2  2  0  3]
 [ 0  0  1  0  3]
 [ 0  0  2  0 41]]


0.7333333333333333

In [251]:
# Results by cross validation
scores_dt = cross_val_score(classifier_dt, x, y, cv=4)
np.mean(scores_dt)

0.6766666666666667

In [252]:
### Random Forest

In [253]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [254]:
y_pred_rf = classifier_rf.predict(x_test)
print(np.concatenate((y_pred_rf.reshape(len(y_pred_rf),1), y_test.reshape(len(y_test),1)),1))

[[4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 2]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 4]
 [1 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [2 4]
 [1 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 1]
 [4 4]
 [4 4]
 [4 1]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [4 3]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


In [255]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)
accuracy_score(y_test, y_pred_rf)

[[ 0  0  0  5]
 [ 1  0  0  7]
 [ 1  0  0  3]
 [ 0  1  0 42]]


0.7

In [256]:
# Results by cross validation
scores_rf = cross_val_score(classifier_rf, x, y, cv=4)
np.mean(scores_rf)

0.7366666666666667